<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Training Assignments Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 10px; }
        .header { text-align: center; margin-bottom: 20px; }
        .filters { margin-bottom: 15px; background-color: #f9f9f9; padding: 10px; font-size: 9px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #ddd; padding: 6px; text-align: left; font-size: 9px; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .footer { margin-top: 20px; text-align: center; font-size: 8px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Training Assignments Report</h1>
        <p>Generated on: {{ $generatedAt->format('F d, Y \a\t g:i A') }}</p>
    </div>

    <div class="filters">
        <h3>Applied Filters:</h3>
        @if(!empty($filters['search']))
            <p><strong>Search:</strong> {{ $filters['search'] }}</p>
        @endif
        @if(!empty($filters['employee_id']))
            <p><strong>Employee ID:</strong> {{ $filters['employee_id'] }}</p>
        @endif
        @if(!empty($filters['training_id']))
            <p><strong>Training ID:</strong> {{ $filters['training_id'] }}</p>
        @endif
        @if(!empty($filters['working_place']))
            <p><strong>Working Place:</strong> {{ $filters['working_place'] }}</p>
        @endif
        @if(!empty($filters['start_date']))
            <p><strong>Start Date:</strong> {{ $filters['start_date'] }}</p>
        @endif
        @if(!empty($filters['end_date']))
            <p><strong>End Date:</strong> {{ $filters['end_date'] }}</p>
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Employee Name</th>
                <th>Designation</th>
                <th>Training Name</th>
                <th>Organizer</th>
                <th>Working Place</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Total Days</th>
                <th>Assigned At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($assignmentsData as $assignment)
                <tr>
                    <td>{{ $assignment->id }}</td>
                    <td>{{ $assignment->employee->name ?? 'N/A' }}</td>
                    <td>{{ $assignment->employee->designation->name ?? 'N/A' }}</td>
                    <td>{{ $assignment->training->name ?? 'N/A' }}</td>
                    <td>{{ $assignment->training->organizer->name ?? 'N/A' }}</td>
                    <td>{{ $assignment->employee->working_place ?? 'N/A' }}</td>
                    <td>{{ $assignment->groupTraining->start_date ? \Carbon\Carbon::parse($assignment->groupTraining->start_date)->format('M d, Y') : 'N/A' }}</td>
                    <td>{{ $assignment->groupTraining->end_date ? \Carbon\Carbon::parse($assignment->groupTraining->end_date)->format('M d, Y') : 'N/A' }}</td>
                    <td>{{ $assignment->groupTraining->total_days ?? 'N/A' }}</td>
                    <td>{{ $assignment->assigned_at ? \Carbon\Carbon::parse($assignment->assigned_at)->format('M d, Y') : 'N/A' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="10" style="text-align: center; font-style: italic;">No assignments found for the selected criteria.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Total Assignments: {{ count($assignmentsData) }}</p>
        <p>This report was automatically generated by the Training Management System.</p>
    </div>
</body>
</html>
